### ISSUE TITLE
new dirsAndFiles.py error

### ISSUE THREAD

**Issue by iwangtoknow** [lfaino/LoReAn#10]
Dear Luigi,
I pulled the latest docker image iprscan_rpMask and met an error with parameter `-sp aspergillus_nidulans`
**After** `### GMAP IS CORRECTLY BUILD ###`
``` bash
Traceback (most recent call last):
  File "/opt/LoReAn/code/lorean.py", line 552, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 137, in main
    augustus_species, err_augustus = logistic.augustus_species_func(home)
  File "/opt/LoReAn/code/dirsAndFiles.py", line 197, in augustus_species_func
    with open(list_file[0]) as bashrc:
IndexError: list index out of range
```
``` python
def augustus_species_func(home):
    check_species = 'augustus --species=help'
    process = subprocess.Popen(check_species, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
    out_augustus, err_augustus = process.communicate()
    list_file = [os.path.join(home, o) for o in os.listdir(home) if
                 os.path.isfile(os.path.join(home, o)) and ".bashrc.lorean" == o]
    with open(list_file[0]) as bashrc:
        for path in bashrc:
            if "AUGUSTUS_CONFIG_PATH" in path:
                augustus_specie_dir = path.split("=~")[1].rsplit()[0]
                augustus_species = [d for d in os.listdir(home + augustus_specie_dir + "species")]
    return augustus_species, err_augustus
``` 
Is the list `list_file` empty here?

**WANG**

**Comment by lfaino** [comment]
Hi Wang,
are you using Singularity? if yes, can you check if in your .bashrc or bashrc.lorean you have to AUGUSTUS_CONFIG paths?

Let me know
Luigi

**Comment by iwangtoknow** [comment]
Hi Luigi,
I'm not using singularity, I'll check the $PATH
Thanks 
**WANG**

**Comment by iwangtoknow** [comment]
Hi Luigi,
`less ~/.bashrc`
``` bash
export AUGUSTUS_CONFIG_PATH=~/augustus/config/
export AUGUSTUS_BIN_PATH=~/augustus/bin
export PATH=$PATH:$AUGUSTUS_BIN_PATH
export PATH=$PATH:/opt/LoReAn/third_party/software/LoReAn/
export PATH=$PATH:/opt/LoReAn/third_party/software/EVidenceModeler-1.1.1
export PATH=$PATH:/opt/LoReAn/third_party/software/gm_et_linux_64/gmes_petap
export PATH=$PATH:/opt/LoReAn/third_party/software/iAssembler-v1.3.2.x64
export PATH=$PATH:/opt/LoReAn/third_party/software/PASApipeline/scripts
export PATH=$PATH:/opt/LoReAn/third_party/software/PASApipeline/
export PATH=$PATH:/opt/LoReAn/third_party/software/Trinity
export PATH=$PATH:/opt/LoReAn/third_party/software/AATpackage-r03052011/bin
export PATH=$PATH:/opt/LoReAn/third_party/software/LoReAn/third_party
export PATH=$PATH:/opt/LoReAn/third_party/software/EVidenceModeler-1.1.1/EvmUtils
export PATH=$PATH:/opt/LoReAn/third_party/software/EVidenceModeler-1.1.1/EvmUtils/misc
export PERL5LIB=/opt/LoReAn/third_party/software/EVidenceModeler-1.1.1/PerlLib
export PATH=$PATH:/opt/LoReAn/third_party/scripts
export PATH=$PATH:/opt/LoReAn/code
export PATH=$PATH:/opt/LoReAn/third_party/software/STAR/bin/Linux_x86_64
export PATH=$PATH:/opt/LoReAn/third_party/software/PASApipeline/bin
export PATH=$PATH:/opt/LoReAn/third_party/software/genometools-1.5.9/bin
export PATH=$PATH:/opt/LoReAn/third_party/software/BRAKER/scripts/
export PATH=$PATH:/opt/LoReAn/third_party/software/interproscan-5.27-66.0
export PATH=$PATH:/opt/LoReAn/third_party/software/TransDecoder-3.0.1
export PATH=$PATH:/opt/LoReAn/third_party/software/TransDecoder-3.0.1/util
export PATH=$PATH:/opt/LoReAn/third_party/conf_files
export PATH=$PATH:/opt/
export PATH=$PATH:/usr/local/RepeatMasker:/usr/local/RepeatScout
export GENEMARK_PATH=/opt/LoReAn/third_party/software/gm_et_linux_64/gmes_petap/
export PATH=$PATH:/opt/LoReAn/third_party/software/PASApipeline/misc_utilities/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/SW/src/
export PERL5LIB=/opt/LoReAn/third_party/scripts/
export PATH=$PATH:/opt/LoReAn/third_party/software/minimap2/
export PATH=$PATH:/opt/LoReAn/third_party/software/SE-MEI/
export SAMTOOLS_PATH=/usr/local/bin/
```
---
And I `export PATH=$PATH:$AUGUSTUS_CONFIG_PATH`
But the error still exist.
**WANG**

**Comment by lfaino** [comment]
Hi Wang,
i know what is going wrong. It is a bug in my coding.

can you please run the below code from your own home directory?
`cp .bashrc .bashrc.lorean`

i think this should fix the issue

Cheers
Luigi

**Comment by iwangtoknow** [comment]
Thanks Luigi.

**WANG**
