### ISSUE TITLE
Raising ValueError when running LoReAn_example 

### ISSUE THREAD

**Issue by Yujiaxin419** [lfaino/LoReAn#29]
I installed LoReAn with command:

`docker run -it --rm -v $PWD:/data lfaino/lorean createUser.py $USER $UID ` 

and tested the example data by:
` lorean.py -t 12 --keep_tmp -a -f -d -sr readsChr.subset.fastq -lr longReadsChr8.fastq -pr subset.prot.fasta -sp JR2 -mg chr8.fasta`

until I met a ValueError:

###GENERATE FASTA FILE FROM CONTIGS### 
###GENERATE FASTA FILE FROM CONTIGS###
###MAPPING CONSENSUS ASSEMBLIES 10:20:17 07-02  ###
###GMAP MAPPING  STARTED AT:    10:20:17 07-02  ###
###BUILD INDEX###
GMAP database existed already: /data/LoReAn_Example/JR2/LoReAn_annotation/run__kr8yxev/gmap_output/chr8.fasta.rename.fasta_GMAPindex --- skipping###MAP#
Traceback (most recent call last):
  File "/opt/LoReAn/code//lorean.py", line 597, in <module>
    main()
  File "/opt/LoReAn/code//lorean.py", line 543, in main
    args.verbose, Fflag=True)
  File "/opt/LoReAn/code/mapping.py", line 403, in gmap
    wd, Fflag, type_out, verbose)
  File "/opt/LoReAn/code/mapping.py", line 134, in gmap_map
    filename = longest_cds(list_fasta[0][1], list_fasta[1][1], verbose, working_dir, filename)
  File "/opt/LoReAn/code/mapping.py", line 192, in longest_cds
    db = gffutils.create_db(gff_file, ':memory:', merge_strategy='create_unique', keep_order=True, transform=transform)
  File "/usr/local/lib/python3.5/dist-packages/gffutils/create.py", line 1288, in create_db
    c.create()
  File "/usr/local/lib/python3.5/dist-packages/gffutils/create.py", line 504, in create
    self._populate_from_lines(self.iterator)
  File "/usr/local/lib/python3.5/dist-packages/gffutils/create.py", line 625, in _populate_from_lines
    raise ValueError("No lines parsed -- was an empty file provided?")
ValueError: No lines parsed -- was an empty file provided?
stu_yujiaxin@d81327d8dc73:/data/LoReAn_Example/JR2$ exit

the image version showed below:
![image](https://user-images.githubusercontent.com/52374093/74052503-f943e880-4a14-11ea-9420-1c58cbd819f6.png)

Could u please do me a favor to help solve this problem.
Thank you.
YU jiaxin

**Comment by Yujiaxin419** [comment]
In my opinion, It seems that generating in Mira pipeline in iAssembler pipeline. MIRA will automatic stop when tmp directory locates in NFS. 

It's the report from `/LoReAn_Example/Crispa/LoReAn_annotation/run/consensus/tmp/seq1_1840071_1852055_405.fasta_Assembly/mira/report`

```
WARNING WARNING WARNING!

It looks like the tmp directory is on a NFS (Network File System) mount. This
will slow down MIRA *considerably* ... by about a factor of 10!
If you don't want that, you have three possibilities:

1) RECOMMENDED! Use -DI:trt to redirect the tmp directory somewhere else on a
   local disk or even SSD.
2) POSSIBLE: put the whole project somewhere else and restart MIRA.
3) ABSOLUTELY NOT RECOMMENDED AT ALL: use "-MI:sonfs=no" to tell MIRA not
   to stop when it finds the tmp directory on NFS.

``` 
I tired to inserted "-DI:trt" to iAssembler.pl pipeline script, then it seems to go on, so I will close this issue. 
Thanks a lot
YU jiaxin

**Comment by lfaino** [comment]
@Yujiaxin419 where did you add the option. I can set this in the docker build and not have the issue anymore

**Comment by Yujiaxin419** [comment]
@lfaino The iAssembler.pl script is showed below. The option must be in COMMON_SETTINGS and tmp directory should be created before. Actually, I don't know whether it is correct or not, but this pipeline finished its work.

```
    255 #################################################################
    256 # iAssembly Pipeline Config File V0.1                           #
    257 # update: 08-26-2009                                            #
    258 # Author: Yi Zheng  yz357 at cornell.edu                        #
    259 #################################################################
    260 
    261 #################################################################
    262 # Format:                                                       #
    263 #                                                               #
    264 # Part    1 --- the order of subpipeline run                    #
    265 # Name    mira --- subpipeline name                             #
    266 # Program mira_pipeline -subpipeline program name               #
    267 # Circle  0 ---                                                 #
    268 #       0 means run did not run this subpipeline                #
    269 #       1 means run once                                        #
    270 # Parameter1    xxx                                             #
    271 # Parameter2    xxx                                             #
    272 #       if have two parameters, it run 2 cycles,                #
    273 @       circle is disabled;                                     #
    274 #################################################################
    275 
    276 
    277 Part    1
    278 Name    mira
    279 Program mira_pipeline
    280 Circle  2
    281 Parameter1      -job=denovo,est,normal,sanger -notraceinfo -GENERAL:kcim=yes,not=$cpus_mira -CO:fnicpst=yes -CL:cpat=no,pec=no,pvlc=no,qc=no,bsq
    281 c=no,mbc=no,emlc=yes,mlcr=0,smlc=0,emrc=yes,mrcr=0,smrc=0 -AL:mrs=$min_identity,mo=$mira_min_overlap -AS:mrl=30,bdq=30 -SK:mnr=yes,pr=$min_ident
    281 ity -DI:trt=/path/to/tmp
    282 Parameter2      -job=denovo,est,normal,sanger -notraceinfo -GENERAL:kcim=yes,not=$cpus_mira -CO:fnicpst=yes -CL:cpat=no,pec=no,pvlc=no,qc=no,bsq
    282 c=no,mbc=no,emlc=yes,mlcr=0,smlc=0,emrc=yes,mrcr=0,smrc=0 -AL:mrs=$min_identity,mo=$mira_min_overlap -AS:mrl=30,bdq=30 -SK:mnr=yes,pr=$min_ident
    282 ity -DI:trt=/path/to/tmp
    283 Parameter3      -job=denovo,est,normal,sanger -notraceinfo -GENERAL:kcim=yes,not=$cpus_mira -CO:fnicpst=yes -CL:cpat=no,pec=no,pvlc=no,qc=no,bsq
    283 c=no,mbc=no,emlc=yes,mlcr=0,smlc=0,emrc=yes,mrcr=0,smrc=0 -AL:mrs=$min_identity,mo=$mira_min_overlap -AS:mrl=30,bdq=30 -SK:mnr=yes,pr=$min_ident
    283 ity -DI:trt=/path/to/tmp
    284 Parameter4      -job=denovo,est,normal,sanger -notraceinfo -GENERAL:kcim=yes,not=$cpus_mira -CO:fnicpst=yes -CL:cpat=no,pec=no,pvlc=no,qc=no,bsq
    284 c=no,mbc=no,emlc=yes,mlcr=0,smlc=0,emrc=yes,mrcr=0,smrc=0 -AL:mrs=$min_identity,mo=$mira_min_overlap -AS:mrl=30,bdq=30 -SK:mnr=yes,pr=$min_ident
    284 ity -DI:trt=/path/to/tmp
```

```
    306 #################################################################
    307 # iAssembler Pipeline Config File V0.1                          #       
    308 # update: 08-26-2009                                            #
    309 # Author: Yi Zheng  yz357 at cornell.edu                        #
    310 #################################################################
    311 
    312 
    313 #################################################################
    314 # Format:                                                       #
    315 #                                                               #
    316 # Part    1 --- the order of subpipeline run                    #
    317 # Name    mira --- subpipeline name                             #
    318 # Program mira_pipeline -subpipeline program name               #
    319 # Circle  0 ---                                                 #
    320 #       0 means run did not run this subpipeline                #
    321 #       1 means run once                                        #
    322 # Parameter1    xxx                                             #
    323 # Parameter2    xxx                                             #
    324 #       if have two parameter, it run 2 cycles,                 #
    325 #       circle is disabled;                                     #
    326 #################################################################
    327 
    328 Part    1
    329 Name    mira
    330 Program mira_pipeline
    331 Circle  2
    332 Parameter1      -job=denovo,est,accurate,454 -notraceinfo -noclipping -GE:not=$cpus_mira 454_SETTINGS -LR:wqf=no:ft=fasta -AS:epoq=no:mrl=30 COM
    332 MON_SETTINGS -AS:nop=4 -SK:not=$cpus_mira:pr=$min_identity:nrr=500:mmhr=100 -CL:pec=no -DI:trt=/path/to/tmp 454_SETTINGS -CL:cpat=no:p
    332 vlc=no:qc=no:bsqc=no:mbc=no:emlc=no:emrc=no:msvs=no -AL:mo=$mira_min_overlap:mrs=$min_identity 
    333 Parameter2      -job=denovo,est,accurate,454 -notraceinfo -noclipping -GE:not=$cpus_mira 454_SETTINGS -LR:wqf=no:ft=fasta -AS:epoq=no:mrl=30 COM
    333 MON_SETTINGS -AS:nop=4 -SK:not=$cpus_mira:pr=$min_identity:nrr=500:mmhr=100 -CL:pec=no -DI:trt=/path/to/tmp 454_SETTINGS -CL:cpat=no:p
    333 vlc=no:qc=no:bsqc=no:mbc=no:emlc=no:emrc=no:msvs=no -AL:mo=$mira_min_overlap:mrs=$min_identity 
    334 Parameter3      -job=denovo,est,accurate,454 -notraceinfo -noclipping -GE:not=$cpus_mira 454_SETTINGS -LR:wqf=no:ft=fasta -AS:epoq=no:mrl=30 COM
    334 MON_SETTINGS -AS:nop=4 -SK:not=$cpus_mira:pr=$min_identity:nrr=500:mmhr=100 -CL:pec=no -DI:trt=/path/to/tmp 454_SETTINGS -CL:cpat=no:p
    334 vlc=no:qc=no:bsqc=no:mbc=no:emlc=no:emrc=no:msvs=no -AL:mo=$mira_min_overlap:mrs=$min_identity 
    335 Parameter4      -job=denovo,est,accurate,454 -notraceinfo -noclipping -GE:not=$cpus_mira 454_SETTINGS -LR:wqf=no:ft=fasta -AS:epoq=no:mrl=30 COM
    335 MON_SETTINGS -AS:nop=4 -SK:not=$cpus_mira:pr=$min_identity:nrr=500:mmhr=100 -CL:pec=no -DI:trt=/path/to/tmp 454_SETTINGS -CL:cpat=no:p
    335 vlc=no:qc=no:bsqc=no:mbc=no:emlc=no:emrc=no:msvs=no -AL:mo=$mira_min_overlap:mrs=$min_identity
    336 Input1  est1.fa
    337 Output2 mira.cmf
    338 Output1 mira.uniseq
```
