### ISSUE TITLE
Problem (write permission) for braker

### ISSUE THREAD

**Issue by nlapalu** [lfaino/LoReAn#31]
Hi,

I get this error with example data using singularity (on a cluster with slurm):

stderr:
```
Traceback (most recent call last):
  File "/opt/LoReAn/code/lorean.py", line 598, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 322, in main
    augustus_file, genemark_file = inputEvm.braker_folder_find(braker_folder)
  File "/opt/LoReAn/code/prepareEvmInputs.py", line 115, in braker_folder_find
    gff = [y for x in os.walk(location) for y in glob(os.path.join(x[0], "augustus.hints.gtf"))][0]
IndexError: list index out of range
```

my command:

```
DATADIR=/home/nlapalu/work/LoReAn/LoReAn_Example/Crispa

singularity exec -B /home/nlapalu/work/LoReAn/augustus_config/:/opt/LoReAn/third_party/software/augustus/config/ -B /home/nlapalu/work/LoReAn/RM_lib
/:/usr/local/RepeatMasker/Libraries/ /home/nlapalu/work/LoReAn/lorean_latest.sif lorean -a -rp ${DATADIR}/repeats.scaffold3.bed -sr ${DATADIR}/Crisp
a.sorted.subsample.bam  -lr ${DATADIR}/scaffold3.long.fasta  -pr ${DATADIR}/scaffold3.prot.fasta -sp ${DATADIR}/crispa ${DATADIR}/scaffold3.fasta -d -f -mg -t 8 --keep_tmp -o annotation_example
```

And I get this error for braker:

braker.error.log
```
ERROR in file /opt/LoReAn/third_party/software/BRAKER/scripts//braker.pl at line 6818
Failed to create new species with new_species.pl, check write permissions in /opt/LoReAn/third_party/software/augustus/config//species directory! Command was perl /opt/LoReAn/third_party/software/augustus/scripts/new_species.pl --species=/home/nlapalu/work/LoReAn/LoReAn_Example/Crispa/crispa --A
UGUSTUS_CONFIG_PATH=/opt/LoReAn/third_party/software/augustus/config/ 1> /dev/null 2>/work/nlapalu/LoReAn/LoReAn_annotation_example/run/braker/error
s/new_species.stderr
```

and errors/new_species.stderr
```
Could not write /opt/LoReAn/third_party/software/augustus/config/species//home/nlapalu/work/LoReAn/LoReAn_Example/Crispa/crispa//home/nlapalu/work/L
oReAn/LoReAn_Example/Crispa/crispa_parameters.cfg. at /opt/LoReAn/third_party/software/augustus/scripts/new_species.pl line 126.
```

I suppose there is a path problem. How to fix it ?
Can I resume the pipeline from the last step ?

Thanks for your help

**Comment by lfaino** [comment]
Hi,
Can you try to download the new image that I made?

Thanks
Luigi

**Comment by nlapalu** [comment]
Hi Luigi,

Still the same error this morning, with a freshly built image:

singularity inspect /home/nlapalu/work/LoReAn/lorean_latest.sif

```
{
        "org.label-schema.build-date": "Monday_15_June_2020_9:12:53_CEST",
        "org.label-schema.schema-version": "1.0",
        "org.label-schema.usage.singularity.deffile.bootstrap": "docker",
        "org.label-schema.usage.singularity.deffile.from": "lfaino/lorean:latest",
        "org.label-schema.usage.singularity.version": "3.0.1-147.g0f938c5"
}
```
Thanks for your help

**Comment by lfaino** [comment]
Dear @nlapalu 
i did check and i got the same error (the last one) because the genemark key was expired.
if you download the new key and you get the same error, try to add -B $HOME:$HOME

**Comment by nlapalu** [comment]
Hi @lfaino 

It's working ! I've never used Singularity before, so I spent a few minutes reading the doc. 
First I fixed the wrong path for the 'new species': a bad concatenation due to the -sp {datadir}/myspecies change to -sp myspecies ! 
Then I tried your solution: -B $HOME:$HOME, but did not work. You have to write the full path:
-B /home/nlapalu:/home/lorean !

With Singularity, the $HOME of the current user is automatically mounted, but I don't know why the $HOME is associated with another path (here: /home/lorean):

```
singularity exec --cleanenv lorean_latest.sif env

DIAMOND_PATH=/usr/local/bin/
CDBTOOLS_PATH=/opt/LoReAn/third_party/software/cdbfasta/
LD_LIBRARY_PATH=:/opt/SW/src/:/.singularity.d/libs
HOME=/home/lorean
...
```

Thanks !
