### ISSUE TITLE
Error when running test data Crispa

### ISSUE THREAD

**Issue by lazlostrange** [lfaino/LoReAn#41]
Hi!

I installed LoReAn via Docker with:
`sudo docker run -it --rm -v /home/hannah/Augustus/config/:/opt/LoReAn/third_party/software/augustus/config/ -v $HOME:/home/lorean  -v $PWD:/data -u $(id -u ${USER}):$(id -g ${USER}) lfaino/lorean:latest lorean -h`
(Docker Image ID: f8bb5db9b404)

and tried to run the pipeline with the example data:
`sudo docker run -it --rm -v /home/hannah/Augustus/config/:/opt/LoReAn/third_party/software/augustus/config/ -v $HOME:/home/lorean -v $PWD:/data -u $(id -u ${USER}):$(id -g ${USER})  lfaino/lorean:latest lorean -a -rp repeats.scaffold3.bed -sr scaffold3.short_1.fastq,scaffold3.short_2.fastq  -lr scaffold3.long.fasta  -pr scaffold3.prot.fasta -sp crispa scaffold3.fasta -d -f -mg -t 6 --keep_tmp`

This is the error I got:
> ###RUNNING BRAKER1 ###
> 100%|#####################################################################| 6/6 [00:07<00:00,  1.32s/it]
> ###RUNNING DIAMOND MAKEDB###
> ###RUNNING DIAMOND ###
> ###RUNNING EXONERATE ###
> 100%|#####################################################################| 176/176 [00:13<00:00, 13.51it/s]
> Traceback (most recent call last):
>   File "/opt/LoReAn/code/lorean.py", line 610, in <module>
>      main()
>   File "/opt/LoReAn/code/lorean.py", line 330, in main
>      augustus_file, genemark_file = inputEvm.braker_folder_find(braker_folder)
>   File "/opt/LoReAn/code/prepareEvmInputs.py", line 115, in braker_folder_find
>      gff = [y for x in os.walk(location) for y in glob(os.path.join(x[0], "augustus.hints.gtf"))][0]
> IndexError: list index out of range

This is the same error as in some other issues, but those solutions did not help my case.
Do you have any suggestions what the problem might be?
Thank you!

**Comment by weihongqi** [comment]
I ran into the same error and notice the augustus config folder downloaded from the repo (https://github.com/lfaino/LoReAn/tree/master/third_party/software) did not have "crispa" as listed as a species ...
