### ISSUE TITLE
RUNNING iASSEMBLER failed

### ISSUE THREAD

**Issue by simoncchu** [lfaino/LoReAn#43]
It has reached the `RUNNING iASSEMBLER ` step:
```
earlier logs...
###UPDATE WITH PASA DATABASE STARTED AT:         03:39:16 17-03 ###
###CREATING CONFIGURATION FILE###
###LOADING GFF3 FILE INTO DATABASE###
###UPDATING GFF3 FILE###
###PARSING OUTPUT###
 ### EVM GFF3 STATS ###
parsed genome node DAGs: 46798
sequence regions: 19 (total length: 669946657)
genes: 46778
protein-coding genes: 46778
mRNAs: 53990
protein-coding mRNAs: 53990
exons: 264596
CDSs: 254114
introns: 631818
###RUNNING iASSEMBLER   19:03:04 17-03  ###
### STARTING ADAPTER ALIGNMENT AND READS ORIENTATION ###
```

But met this error:
```
Traceback (most recent call last):
  File "/opt/LoReAn/code/lorean.py", line 610, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 498, in main
    args.max_intron_length, args.verbose, stranded_value)
  File "/opt/LoReAn/code/manipulateSeq.py", line 177, in filterLongReads
    out_filename_oriented, threads, min_length)
  File "/opt/LoReAn/code/align.py", line 61, in adapter_alignment
    for adapter in SeqIO.parse(adapter_sequence, "fasta"):
  File "/usr/local/lib/python3.6/dist-packages/Bio/SeqIO/__init__.py", line 655, in parse
    for r in i:
  File "/usr/local/lib/python3.6/dist-packages/Bio/SeqIO/FastaIO.py", line 172, in FastaIterator
    for title, sequence in SimpleFastaParser(handle):
  File "/usr/local/lib/python3.6/dist-packages/Bio/SeqIO/FastaIO.py", line 45, in SimpleFastaParser
    for line in handle:
TypeError: 'bool' object is not iterable
```
Any suggestions?

**Comment by lfaino** [comment]
Lorean tries to find the adapter used for library preparation. Maybe it can con find it.

can you send me the command that you run?

Luigi

**Comment by simoncchu** [comment]
Thank you for your reply. Here is the command:
```
singularity exec -B ${WFOLDER}:/home/ -B ${CONFIG}:/opt/LoReAn/third_party/software/augustus/config/ -B ${LIB}:/usr/local/RepeatMasker/Libraries/ ${MODEL}"lorean_latest.sif" lorean \
-pr /home/apple_small.pep.fasta  -sp malus_domestica -d -t 16 -kt -sr /home/filter_RNA_1.fastq,/home/filter_RNA_2.fastq -lr /home/longreads.hq.fastq -o ${WFOLDER} /home/rmsked.fa
```
We are using HiFi long reads, and the adapter has been removed. Could we skip the adapter trimming step?

**Comment by lfaino** [comment]
Can you try without the -d option?

**Comment by simoncchu** [comment]
Hi @lfaino , after run without -d option, I still get the same error. 
Any other suggestions? Thank you a lot!

**Comment by simoncchu** [comment]
Also, in the `temporary` folder, there is a file `Final.evm.update.gff3` under folder `run/PASA`. Can I use this as the final results? Thanks in advance!
